# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3d1da31499f0007bce8983b5dffff516232bde712673cf9d44a3da9ee85df7b77f698434d25188989037ee8711538d7a897cd9b234aae930a777d13f5f6fe60e

test:
  secret_key_base: d81e296a3645162f019f7338577e81ecf119d3a09f69e409ff110d653e17def4badac100f7c673fa1a102c8b5974160dc21758cf0dab2b5912d545bfd99fd49e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
